---
- hosts: ubuntu
  become: yes

  tasks:

  - name: Actualizar Paquetes
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
    notify: Reinicio_Sistema
  
  - name: Instalar Fail2BAN
    ansible.builtin.apt:
      name: fail2ban
      state: present
  
  - name: Configuracion Fail 2 BAN # Se asegura que la configuracion de Fail2Ban sea la correcta para SSH
    ansible.builtin.template:
      src: ../templates/jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      mode: u=rw,g=r,o=r
    notify: Reiniciar_F2B


  - name: Iniciar y habilitar Fail2BAN
    ansible.builtin.service:
      name: fail2ban
      enabled: yes
      state: started    

  - name: No Permitir Login Root
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: '^PermitRootLogin'
      line: PermitRootLogin no
    notify: Reinicio_Daemon_SSH

  - name: No Permitir iniciar sesion con Password
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: '^PasswordAuthentication'
      line: PasswordAuthentication no
    notify: Reinicio_Daemon_SSH
  
  - name: Modificar linea de archivo 50-cloud-init
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      regexp: '^PasswordAuthentication yes'
      state: absent  
    notify: Reinicio_Daemon_SSH


  - name: Asegurarse que UFW Este habilitado y ejecutandose bloqueando trafico incoming
    community.general.ufw:
      state: enabled
      policy: reject
      direction: incoming
    notify: Recargar_UFW

  - name: Habilitar Open SSH
    community.general.ufw:
      rule: allow
      port: 22
      proto: tcp
    notify: Recargar_UFW
  


  handlers:

  - name: Reinicio_Sistema
    ansible.builtin.reboot:

  - name: Reinicio_Daemon_SSH
    ansible.builtin.systemd_service:
      name: ssh
      state: restarted

  - name: Recargar_UFW
    ansible.builtin.service:
      name: ufw
      state: restarted

  - name: Reiniciar_F2B
    ansible.builtin.service:
      name: fail2ban
      state: restarted
    

      
